//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hr_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class E_Work
    {
        public int ID { get; set; }
        public string Employee_Name { get; set; }
        public string Duration { get; set; }
        public string Price { get; set; }
        public string Status { get; set; }
        public string Start_Date { get; set; }
        public string End_Date { get; set; }
        [NotMapped]
        public List<Employee> Employename { get; set; }
    }
}
