//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hr_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class employeeLogin
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        [NotMapped]
        public List<Employee> Employename { get; set; }
    }
}
