//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hr_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class EmployeeSalary
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Fild requred.")]

        public string Name { get; set; }
        [Required(ErrorMessage = "Fild requred.")]

        public string Salary { get; set; }
        [Required(ErrorMessage = "Fild requred.")]

        public string Account_No { get; set; }
        public string Starting_Salary { get; set; }
        public string Increasing_Salary { get; set; }
        [Required(ErrorMessage = "Fild requred.")]

        public string Date { get; set; }
        [Required(ErrorMessage = "Fild requred.")]

        public string Status { get; set; }
        [NotMapped]
        public List<Employee> Employename { get; set; }
    }
}
